### PR TITLE
Compress html to genereate .h with byte array as part of build process

### PR DESCRIPTION
**Pull request by longrackslabs**
Enhanced the build process to automatically compress html files into the .h file bytearray.  For example, setuppage.html -> setuppage.h  that contains the compressed bytearray of the setuppage.html. the .h file is only generated if it is missing or the .html file is newer.

 I updated the README on the process and the 2 requirements (python, qpdf library).

This should work for other files like updatepage.html by adding them to the list in compress_html.py.  I did not do that as I am only testing the pages on the device.  Just add the html files to the list.

### CODE REVIEW

**Comment by DutchDevelop** [comment]
Conflicts must be resolved before merging

**Comment by longrackslabs** [comment]
setupPage.h is deleted from the branch/git as it will be generated now (as setuppage.h> not hand edited so it doesn't need to get checked in anymore.  the file shows as deleted in the 'files changed' of the PR - i though git would handle this in the merge? Or do you need to deleted from main/master?

**Comment by DutchDevelop** [comment]
Not sure, it doesn't allow me to commit. Doesn't say what the cause is either on github mobile

**Comment by longrackslabs** [comment]
Ok I'll see if I can resolve the conflicts

**Comment by longrackslabs** [comment]
ok, looks like I needed to 'git rm setupPage.h" in addition to deleting the file.  I synced my fork to the latest and did a clean test merge.

**Pull request merged**
